#!/usr/bin/python3
# SPDX-License-Identifier: 0BSD
#
# Checks web pages for obsolete or discouraged HTML,
# written by Hanno Böck, https://hboeck.de/

import argparse
import urllib.request

import lxml.html

ap = argparse.ArgumentParser()
ap.add_argument("url")

args = ap.parse_args()

u = urllib.request.urlopen(args.url)
ht = lxml.html.parse(u)

for css in ht.findall(".//link[@rel='stylesheet']"):
    csstype = css.get("type")
    if csstype == "text/css":
        # https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/style#type
        print('WARNING: type="text/css" for CSS not needed in HTML5')
    elif csstype:
        print(f"WARNING: unknown stylesheet type {csstype}")

if ht.findall(".//link[@rel='shortcut icon']"):
    print('WARNING: Use of obsolete IE rel="shortcut icon" (use rel="icon")')

if ht.findall(".//meta[@http-equiv='content-language']"):
    # https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta/http-equiv
    # https://www.w3.org/TR/2011/WD-html-markup-20110113/meta.http-equiv.content-language.html
    print("WARNING: <meta http-equiv='content-language' ...> is obsolete, use <html lang='xx'>")

metacharset = ht.findall(".//meta[@charset]")
if len(metacharset) > 1:
    print("ERROR: More than one <meta charset=...> element")

for httpequiv in ht.findall(".//meta[@http-equiv]"):
    heqvalue = httpequiv.get("http-equiv")
    # lowercase to find cases where people use, e.g., Content-Type
    heqvalue_l = heqvalue.lower()
    if heqvalue_l == "content-type":
        if metacharset:
            # https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset
            print("ERROR: Both <meta charset=...> and <meta http-equiv='content-type' ...> used")
        else:
            # https://blog.whatwg.org/meta-charset
            print("WARNING: Old-style <meta http-equiv='content-type' ...>, use <meta charset=...>")
    elif heqvalue_l == "content-language":
        print("WARNING: Obsolete <meta http-equiv='content-language' ...>, use <html lang='...'>")
    elif heqvalue_l == "x-ua-compatible":
        print("WARNING: <meta http-equiv='X-UA-Compatible' ...> is obsolete (IE feature)")
    elif heqvalue_l == "set-cookie":
        # https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-http-equiv-set-cookie
        print("WARNING: <meta http-equiv='set-cookie' ...> is ignored by modern browser")
