#!/usr/bin/python3
# SPDX-License-Identifier: 0BSD
#
# Checks web pages for obsolete or discouraged HTML,
# written by Hanno Böck, https://hboeck.de/

import argparse
import urllib.request

import lxml.html


def _warn(msg):
    print(f"WARNING: {msg}")


def _safeesc(s):
    return repr(s).encode("unicode_escape").decode().strip("'")


ap = argparse.ArgumentParser()
ap.add_argument("url")

args = ap.parse_args()

with urllib.request.urlopen(args.url) as u:
    headers = u.getheaders()
    ht = lxml.html.parse(u)

obsoleteheaders = ["x-ua-compatible", "x-xss-protection",
                   "expect-ct", "public-key-pins", "pragma",
                   "warning"]
for h, _v in headers:
    header = h.lower()
    if header in obsoleteheaders:
        _warn(f"{header} header is obsolete")

for css in ht.findall(".//link[@rel='stylesheet']"):
    csstype = css.get("type")
    if csstype == "text/css":
        # https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/style#type
        print('WARNING: type="text/css" for CSS not needed in HTML5')
    elif csstype:
        print(f"WARNING: unknown stylesheet type {csstype}")

if ht.findall(".//link[@rel='shortcut icon']"):
    print('WARNING: Use of obsolete IE rel="shortcut icon" (use rel="icon")')

metacharset = ht.findall(".//meta[@charset]")
if len(metacharset) > 1:
    print("ERROR: More than one <meta charset=...> element")
if metacharset:
    m = ht.findall(".//head/*[1]")
    if m[0] != metacharset[0]:
        # https://code.google.com/archive/p/doctype-mirror/wikis/MetaCharsetAttribute.wiki
        _warn("<meta charset=...> should be first in <head>")

# Values from here minus the ones that are obsolete or discouraged
# https://html.spec.whatwg.org/#attr-meta-http-equiv
validequiv = ["default-style", "refresh", "content-security-policy"]

for httpequiv in ht.findall(".//meta[@http-equiv]"):
    heqvalue = httpequiv.get("http-equiv")
    # lowercase to find cases where people use, e.g., Content-Type
    heqvalue_l = heqvalue.lower()
    if heqvalue_l in validequiv and heqvalue != heqvalue_l:
        print("WARNING: http-equiv values should be lowercase")
    if heqvalue_l not in validequiv:
        if heqvalue_l == "content-language":
            # https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meta/http-equiv
            # https://www.w3.org/TR/2011/WD-html-markup-20110113/meta.http-equiv.content-language.html
            _warn("Replace httpequiv='content-language' with <html lang=...>")
        elif heqvalue_l == "content-type":
            # https://html.spec.whatwg.org/multipage/semantics.html#attr-meta-charset
            _warn("Replace http-equiv='content-type' with <meta charset=...>")
        else:
            # Notes about obsolete http-equiv values:
            # * set-cookie is ignored according to whatwg spec
            # * x-ua-compatible is an Internet Explorer feature
            # * content-style-type/content-script-type were part of HTML 4, removed in HTML 5
            safeheq = _safeesc(heqvalue)
            _warn(f"http-equiv='{safeheq}' is obsolete or invalid")
